import type { Locale } from "@/lib/i18n";

export default async function AboutPage({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params;
  const text = {
    fa: { kicker: "درباره مندگار", title: "تجربه را از صفر می‌سازیم.", intro: "مندگار یک شرکت تجربه‌محور برای رویدادها و نمایشگاه‌هاست؛ جایی که ایده، فضا، فناوری و اجرا در یک مسیر واحد قرار می‌گیرند.", title2: "چطور فکر می‌کنیم", body: "ما به جای اضافه کردن افکت، ابتدا دلیل حضور هر عنصر را پیدا می‌کنیم. تجربه باید روشن، انسانی، قابل اجرا و در نهایت به‌یادماندنی باشد.", principles: ["ایده قبل از ابزار", "جزئیات با دلیل", "اثبات با کار واقعی", "آماده برای همکاری"] },
    en: { kicker: "About Mandegar", title: "We build the experience from zero.", intro: "Mandegar is an experience company for events and exhibitions, connecting idea, space, technology and delivery into one journey.", title2: "How we think", body: "Instead of adding effects, we first find the reason for every element. An experience should be clear, human, deliverable and ultimately memorable.", principles: ["Idea before tool", "Detail with purpose", "Proof through real work", "Ready to collaborate"] },
    ar: { kicker: "عن مندگار", title: "نبني التجربة من الصفر.", intro: "مندگار شركة تجارب للفعاليات والمعارض، تربط الفكرة والمساحة والتقنية والتنفيذ في رحلة واحدة.", title2: "كيف نفكر", body: "بدلاً من إضافة المؤثرات، نبحث أولاً عن سبب كل عنصر. يجب أن تكون التجربة واضحة وإنسانية وقابلة للتنفيذ ولا تُنسى.", principles: ["الفكرة قبل الأداة", "تفصيل له هدف", "الإثبات بالعمل الحقيقي", "جاهزون للتعاون"] },
  }[locale];
  return <div className="aboutPage"><section className="pageHero"><div className="pageWidth"><div className="sectionKicker">01 / {text.kicker}</div><h1>{text.title}</h1><p>{text.intro}</p></div></section><section className="sectionPad"><div className="pageWidth aboutGrid"><div><div className="sectionKicker">02 / {text.title2}</div><h2 className="aboutStatement">{text.title2}</h2></div><div><p className="sectionLeadText">{text.body}</p><div className="principles">{text.principles.map((principle, index) => <div className="principle" key={principle}><strong>0{index + 1}</strong><p>{principle}</p></div>)}</div></div></div></section><section className="sectionPad trustSection"><div className="pageWidth splitIntro"><div className="sectionKicker">03 / {locale === "fa" ? "مدل جغرافیایی" : locale === "ar" ? "النموذج الجغرافي" : "Geographic model"}</div><div><h2>{locale === "fa" ? "ساخت محلی. آماده برای همکاری جهانی." : locale === "ar" ? "بُني محلياً. جاهزون للتعاون عالمياً." : "Built locally. Ready to collaborate globally."}</h2><p>{locale === "fa" ? "مندگار در ایران ریشه دارد و در بازارهای دیگر بر اساس نیاز پروژه، امکان همکاری مستقیم یا مشارکت با تیم‌های محلی مورد اعتماد را بررسی می‌کند." : locale === "ar" ? "مندگار متجذر في إيران، وفي الأسواق الأخرى يدرس العمل المباشر أو الشراكة مع فرق محلية موثوقة حسب متطلبات المشروع." : "Mandegar is rooted in Iran. In other markets, we consider direct work or trusted local partnerships according to each project’s needs."}</p></div></div></section></div>;
}
